import type { Metadata } from 'next';
import { Inter as FontSans, JetBrains_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { cn } from '@/utils/cn';
import { Provider as TooltipProvider } from '@/components/ui/tooltip';
import { NotificationProvider } from '@/components/ui/notification-provider';
import Navbar from '@/components/navbar';
import { AuthProvider } from '@/utils/supabase/AuthContext';
import { AudioProvider } from '@/contexts/AudioContext';
import GlobalAudioPlayer from '@/components/layout/global-audio-player';
import I18nInit from '@/components/I18nInit';

const inter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const geistMono = localFont({
  src: './fonts/GeistMono[wght].woff2',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='zh'
      suppressHydrationWarning
      className={cn(inter.variable, geistMono.variable, 'antialiased')}
    >
      <body className='bg-bg-white-0 text-text-strong-950'>
        <I18nInit />
        <AuthProvider>
          <ThemeProvider attribute='class' defaultTheme='light'>
            <TooltipProvider>
              <div className='flex min-h-screen flex-col'>
                <div className='border-b border-stroke-soft-200'>
                  <div className='mx-auto w-full max-w-[1440px]'>
                    <Navbar />
                  </div>
                </div>
                <div className='mx-auto w-full max-w-[1440px] mt-[4.5rem]'>
                  <main className='flex flex-1 flex-col '>
                    <AudioProvider>
                      {children}
                      <GlobalAudioPlayer />
                    </AudioProvider>
                  </main>
                </div>
              </div>
            </TooltipProvider>
          </ThemeProvider>
        </AuthProvider>
        <NotificationProvider />
      </body>
    </html>
  );
}
